options:
  avi-controller-ip:
    type: string
    default:
    description: "IP of Avi controller"
  avi-controller-username:
    type: string
    default: admin
    description: "Username for Avi controller"
  avi-controller-password:
    type: string
    default:
    description: "Password for Avi controller"
  avi-controller-tenant:
    type: string
    default: admin
    description: "Tenant of Avi controller"
  avi-controller-version:
    type: string
    default: 18.1.3
    description: "Version of Avi controller"

